FROM python:3.8-slim
# Allow statements and log messages to immediately appear in the Knative logs
ENV PYTHONUNBUFFERED True

# RUN apt-get update && apt-get install -y gcc python3-opencv g++ && apt-get -y clean && apt-get -y autoremove

# Copy local code to the container image.
ENV APP_HOME /cerulean_cloud
WORKDIR $APP_HOME
COPY cerulean_cloud/ /cerulean_cloud/

# Install production dependencies.
RUN pip install -r cloud_run_orchestrator/requirements.txt

# Run the web service on container startup. Here we use the gunicorn
# webserver, with one worker process and 8 threads.
# For environments with multiple CPU cores, increase the number of workers
# to be equal to the cores available.
# Timeout is set to 0 to disable the timeouts of the workers to allow Cloud Run to handle instance scaling.
CMD exec uvicorn --port $PORT --host 0.0.0.0 cerulean_cloud.cloud_run_orchestrator.handler:app

