FROM python:3.9-slim AS build-env

WORKDIR /app

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

COPY cerulean_cloud/cloud_run_orchestrator/requirements.txt ./requirements.txt

RUN pip install \
      --no-input \
      --disable-pip-version-check \
      --compile \
      --no-warn-script-location \
      --isolated \
      --target ./site-packages \
      -r ./requirements.txt
RUN pip install \
      --isolated \
      --no-cache-dir \
      --disable-pip-version-check \
      'cyclonedx-bom<4.0.0'
RUN pip freeze --path ./site-packages | cyclonedx-py -r -i - --purl-bom-ref --format xml -o sbom.xml --force
RUN rm requirements.txt

COPY cerulean_cloud/__init__.py /app/cerulean_cloud/
COPY cerulean_cloud/common /app/cerulean_cloud/common
COPY cerulean_cloud/cloud_run_orchestrator /app/cerulean_cloud/cloud_run_orchestrator
COPY cerulean_cloud/cloud_run_offset_tiles /app/cerulean_cloud/cloud_run_offset_tiles
COPY cerulean_cloud/cloud_function_ais_analysis /app/cerulean_cloud/cloud_function_ais_analysis

FROM gcr.io/distroless/python3-debian11:debug-nonroot AS final

USER nonroot:nonroot

COPY --chown=nonroot:nonroot --chmod=500 --from=build-env /app /app

WORKDIR /app

ENV PYTHONPATH=/app/site-packages
ENV PYTHONUNBUFFERED=1

########################
# Use the following environment variables to configure uvicorn
#
# - UVICORN_PORT environment variable to set the port on which unicorn shall listin for incoming connections
# - WEB_CONCURRENCY Number of worker processes. Defaults to 1
#   For environments with multiple CPU cores, increase the number of workers
#   to be equal to the cores available.
ENTRYPOINT [ "python", "-m", "uvicorn", "cerulean_cloud.cloud_run_orchestrator.handler:app", "--host", "0.0.0.0", "--proxy-headers" ]
