# Stage 1
FROM public.ecr.aws/sam/build-python3.9

WORKDIR /var/task

COPY cerulean_cloud/titiler_sentinel/requirements.txt ./requirements.txt
COPY cerulean_cloud/titiler_sentinel/handler.py handler.py
COPY cerulean_cloud/titiler_sentinel/templates/ ./templates
COPY cerulean_cloud/__init__.py ./cerulean_cloud/
COPY cerulean_cloud/common/__init__.py cerulean_cloud/common/auth.py cerulean_cloud/common/

# Use after upgrade of Pulumi Docker to >= 4
# COPY --chown=root:root --chmod=400 Dockerfiles/scripts/titiler-entrypoint.sh /entrypoint.sh
COPY Dockerfiles/scripts/titiler-entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "/bin/sh", "/entrypoint.sh" ]
