name: Deploy Cerulean Infratructure
description: |-
  This action deploys the Cerulean infrastructure
inputs:
  environment:
    description: |-
      Target environment of infrastructure deployment
    required: true
  python-version:
    description: |-
      Which Python version to use
    default: '3.9'
  pulumi-version:
    description: |-
      Which Pulumi version to use
    required: true
  pulumi-stack-passphrase:
    description: |-
      The passphrahse to encrypt secrets in the Pulumi stack
    required: true
runs:
  using: "composite"
  steps:
    - name: Clean all existing Docker images
      id: prune-docker
      shell: bash
      run: |
        docker image prune -a -f
        df -H

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Get pip cache dir
      id: pip-cache
      shell: bash
      run: |
        python -m pip install pip --upgrade
        echo "PIP_CACHE_DIR=$(python -m pip cache dir)" >> $GITHUB_ENV

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ${{ env.PIP_CACHE_DIR }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Configure GCP Credentials
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/734798842681/locations/global/workloadIdentityPools/my-pool/providers/gh-provider"
        service_account: "git-cerulean-cloud@cerulean-338116.iam.gserviceaccount.com"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::162277344632:role/CeruleanCloudDeploy
        aws-region: eu-central-1

    - name: Configure docker
      shell: bash
      run: |
        gcloud auth configure-docker -q

    - name: Install Pulumi requirements
      shell: bash
      run: |
        pip install -r requirements-pulumi.txt

    - name: Build Container Images
      uses: pulumi/actions@v5
      id: pulumi-images
      env:
        PULUMI_CONFIG_PASSPHRASE: ${{ inputs.pulumi-stack-passphrase }}
      with:
        pulumi-version: ${{ inputs.pulumi-version }}
        work-dir: images/
        command: up
        stack-name: ${{ inputs.environment }}
        parallel: 1

    - name: Prune Docker environment
      shell: bash
      run: |
        docker container prune -f
        docker buildx prune -f
        docker images

    # Copy shared database_client.py files
    - name: Copy Shared File
      shell: bash
      run: |
        mkdir -p cerulean_cloud/cloud_function_ais_analysis/cerulean_cloud/
        cp cerulean_cloud/database_client.py cerulean_cloud/cloud_function_ais_analysis/cerulean_cloud/database_client.py
        cp cerulean_cloud/database_schema.py cerulean_cloud/cloud_function_ais_analysis/cerulean_cloud/database_schema.py
        cp cerulean_cloud/__init__.py cerulean_cloud/cloud_function_ais_analysis/cerulean_cloud/__init__.py

    - name: Deploy Infrastructure
      uses: pulumi/actions@v5
      id: pulumi
      env:
        PULUMI_CONFIG_PASSPHRASE: ${{ inputs.pulumi-stack-passphrase }}
        MODEL: ${{ steps.pulumi-images.outputs.model }}
      with:
        pulumi-version: ${{ inputs.pulumi-version }}
        command: up
        stack-name: ${{ inputs.environment }}
        refresh: true
        diff: true
        comment-on-summary: true

    - name: Start Google Cloud SQL Proxy
      uses: wagnerpereira/gce-cloudsql-proxy-action@v2
      with:
        instance: ${{ steps.pulumi.outputs.database_instance_name }}

    - name: Run database migrations
      shell: bash
      env:
        DB_URL: ${{ steps.pulumi.outputs.database_url_alembic }}
      run: |
        pip install -r requirements.txt && alembic upgrade head
