"""Constants for Automatic Source Association handler"""

# TEMPORAL PARAMETERS FOR AIS
HOURS_BEFORE = 12
HOURS_AFTER = 2
TIMESTEPS_PER_HOUR = 6
NUM_TIMESTEPS = HOURS_BEFORE * TIMESTEPS_PER_HOUR

# BUFFERING PARAMETERS FOR AIS
AIS_PROJECT_ID = "world-fishing-827"
AIS_BUFFER = 20000  # buffer around GRD envelope to capture AIS
SPREAD_RATE = 10000  # meters/hour perpendicular to vessel track

D_FORMAT = "%Y-%m-%d"
T_FORMAT = "%Y-%m-%d %H:%M:%S"


# WEIGHTING PARAMETERS FOR AIS
W_TEMPORAL = 2.0
W_PROXIMITY = 1.0
W_PARITY = 1.0
AIS_REF_TIME_OVER = 600.0  # Seconds
AIS_REF_TIME_UNDER = 10000.0  # Seconds
SENSITIVITY_PARITY = 5.77  # 4/ln(2) calculated to make a 45º angle have a score of 0.5 decrease to be more lenient

# COLLATION PARAMETERS
# https://skytruth.atlassian.net/browse/TECH-2371
INFRA_MEAN = 0.3
INFRA_STD = 0.16
VESSEL_MEAN = 0.576
VESSEL_STD = 0.163

# ANALYSIS PARAMETERS FOR INFRASTRUCTURE
NUM_VERTICES = 10
CLOSING_BUFFER = 500
INFRA_REF_DIST = 3000
DECAY_FACTOR = 4.0
MIN_AREA_THRESHOLD = 0.1
