name: Test and Deploy
on:
  push:
    branches: [main]
    tags:
      - "**"
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-test.txt
          python -m pip install -r requirements.txt

      - name: Run pytest
        run: python -m pytest

      # Run pre-commit
      - name: run pre-commit
        run: pre-commit run --all-files

  preview-test:
    name: Preview [TEST]
    needs: [tests]
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Configure GCP Credentials
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/734798842681/locations/global/workloadIdentityPools/my-pool/providers/gh-provider"
          service_account: "git-cerulean-cloud@cerulean-338116.iam.gserviceaccount.com"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::162277344632:role/CeruleanCloudDeploy
          aws-region: eu-central-1

      - run: pip install -r requirements.txt
      - uses: pulumi/actions@v3
        env:
          PULUMI_CONFIG_PASSPHRASE: "test"
        with:
          command: preview
          stack-name: test
          cloud-url: gs://cerulean-cloud-state
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}


  deploy-test:
    name: Deploy [TEST]
    needs: [preview-test]
    runs-on: ubuntu-latest
    environment: test
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Configure GCP Credentials
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/734798842681/locations/global/workloadIdentityPools/my-pool/providers/gh-provider"
          service_account: "git-cerulean-cloud@cerulean-338116.iam.gserviceaccount.com"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::162277344632:role/CeruleanCloudDeploy
          aws-region: eu-central-1

      - run: pip install -r requirements.txt
      - uses: pulumi/actions@v3
        env:
          PULUMI_CONFIG_PASSPHRASE: "test"
        with:
          command: up
          stack-name: test
          cloud-url: gs://cerulean-cloud-state

  preview-staging:
    name: Preview [STAGING]
    needs: [tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Configure GCP Credentials
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/734798842681/locations/global/workloadIdentityPools/my-pool/providers/gh-provider"
          service_account: "git-cerulean-cloud@cerulean-338116.iam.gserviceaccount.com"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::162277344632:role/CeruleanCloudDeploy
          aws-region: eu-central-1

      - run: pip install -r requirements.txt
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: staging
          cloud-url: gs://cerulean-cloud-state
        env:
          PULUMI_CONFIG_PASSPHRASE: ""

  deploy-staging:
    name: Deploy [STAGING]
    needs: [preview-staging]
    runs-on: ubuntu-latest
    environment: staging
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Configure GCP Credentials
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/734798842681/locations/global/workloadIdentityPools/my-pool/providers/gh-provider"
          service_account: "git-cerulean-cloud@cerulean-338116.iam.gserviceaccount.com"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::162277344632:role/CeruleanCloudDeploy
          aws-region: eu-central-1

      - run: pip install -r requirements.txt
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: staging
          cloud-url: gs://cerulean-cloud-state
        env:
          PULUMI_CONFIG_PASSPHRASE: ""

  preview-production:
    name: Preview [PRODUCTION]
    needs: [tests]
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Configure GCP Credentials
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/734798842681/locations/global/workloadIdentityPools/my-pool/providers/gh-provider"
          service_account: "git-cerulean-cloud@cerulean-338116.iam.gserviceaccount.com"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::162277344632:role/CeruleanCloudDeploy
          aws-region: eu-central-1

      - run: pip install -r requirements.txt
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: production
          cloud-url: gs://cerulean-cloud-state
        env:
          PULUMI_CONFIG_PASSPHRASE: ""

  deploy-production:
    name: Deploy [PRODUCTION]
    needs: [preview-production]
    runs-on: ubuntu-latest
    environment: production
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Configure GCP Credentials
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/734798842681/locations/global/workloadIdentityPools/my-pool/providers/gh-provider"
          service_account: "git-cerulean-cloud@cerulean-338116.iam.gserviceaccount.com"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::162277344632:role/CeruleanCloudDeploy
          aws-region: eu-central-1

      - run: pip install -r requirements.txt
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: production
          cloud-url: gs://cerulean-cloud-state
        env:
          PULUMI_CONFIG_PASSPHRASE: ""
